parameters:
#    rodas_xml.example.class: Ociosos\RodasXMLBundle\Example

services:
#    rodas_xml.example:
#        class: %rodas_xml.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
