<?php

namespace Proxies\__CG__\Ociosos\ComunBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Centro extends \Ociosos\ComunBundle\Entity\Centro implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setSiglas($siglas)
    {
        $this->__load();
        return parent::setSiglas($siglas);
    }

    public function getSiglas()
    {
        $this->__load();
        return parent::getSiglas();
    }

    public function setDireccion($direccion)
    {
        $this->__load();
        return parent::setDireccion($direccion);
    }

    public function getDireccion()
    {
        $this->__load();
        return parent::getDireccion();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setDirector($director)
    {
        $this->__load();
        return parent::setDirector($director);
    }

    public function getDirector()
    {
        $this->__load();
        return parent::getDirector();
    }

    public function setREEUP($rEEUP)
    {
        $this->__load();
        return parent::setREEUP($rEEUP);
    }

    public function getREEUP()
    {
        $this->__load();
        return parent::getREEUP();
    }

    public function setOrganizacion(\Ociosos\ComunBundle\Entity\Organizacion $organizacion)
    {
        $this->__load();
        return parent::setOrganizacion($organizacion);
    }

    public function getOrganizacion()
    {
        $this->__load();
        return parent::getOrganizacion();
    }

    public function setMunicipio(\Ociosos\ComunBundle\Entity\Municipio $municipio)
    {
        $this->__load();
        return parent::setMunicipio($municipio);
    }

    public function getMunicipio()
    {
        $this->__load();
        return parent::getMunicipio();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'siglas', 'direccion', 'telefono', 'email', 'director', 'rEEUP', 'organizacion', 'municipio');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}