parameters:
#    comun.example.class: Ociosos\ComunBundle\Example

services:
#    comun.example:
#        class: %comun.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    captcha:
        class: ComunBundle\Captcha
        arguments: [request]