<?php

namespace Proxies\__CG__\Ociosos\ComunBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Producto extends \Ociosos\ComunBundle\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setCodigo($codigo)
    {
        $this->__load();
        return parent::setCodigo($codigo);
    }

    public function getCodigo()
    {
        $this->__load();
        return parent::getCodigo();
    }

    public function setFechaExportacion(\DateTime $fechaExportacion)
    {
        $this->__load();
        return parent::setFechaExportacion($fechaExportacion);
    }

    public function getFechaExportacion()
    {
        $this->__load();
        return parent::getFechaExportacion();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setUM($uM)
    {
        $this->__load();
        return parent::setUM($uM);
    }

    public function getUM()
    {
        $this->__load();
        return parent::getUM();
    }

    public function setCantidad($cantidad)
    {
        $this->__load();
        return parent::setCantidad($cantidad);
    }

    public function getCantidad()
    {
        $this->__load();
        return parent::getCantidad();
    }

    public function setPrecioMN($precioMN)
    {
        $this->__load();
        return parent::setPrecioMN($precioMN);
    }

    public function getPrecioMN()
    {
        $this->__load();
        return parent::getPrecioMN();
    }

    public function setPrecioMLC($precioMLC)
    {
        $this->__load();
        return parent::setPrecioMLC($precioMLC);
    }

    public function getPrecioMLC()
    {
        $this->__load();
        return parent::getPrecioMLC();
    }

    public function setAlmacen(\Ociosos\ComunBundle\Entity\Almacen $almacen)
    {
        $this->__load();
        return parent::setAlmacen($almacen);
    }

    public function getAlmacen()
    {
        $this->__load();
        return parent::getAlmacen();
    }

    public function setCategoria(\Ociosos\ComunBundle\Entity\Categoria $categoria)
    {
        $this->__load();
        return parent::setCategoria($categoria);
    }

    public function getCategoria()
    {
        $this->__load();
        return parent::getCategoria();
    }

    public function setCentro(\Ociosos\ComunBundle\Entity\Centro $centro)
    {
        $this->__load();
        return parent::setCentro($centro);
    }

    public function getCentro()
    {
        $this->__load();
        return parent::getCentro();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'codigo', 'fechaExportacion', 'estado', 'uM', 'cantidad', 'precioMN', 'precioMLC', 'almacen', 'categoria', 'centro');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}